version: '3.8'
services:
  koth_server:
    container_name: koth_server
    image: kothserver:1.0
    networks: 
      - frontend
    volumes: 
      - ./scores.json/:/app/scores.json
      - ./settings.yaml:/app/settings.yaml
      # For keeping track of local time
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    restart: unless-stopped
    ports:
      - 8080:8080

networks:
  frontend: